apiVersion: apps/v1
kind: Deployment  
metadata:
  name: web-deployment
  labels:
    app: webapp
  namespace: web
spec: 
  selector:
    matchLabels:
      app: webapp
  replicas: 3
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp-container
          image: webapp-img:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000

