apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-persistent-claim
  namespace: web
  labels:
    app: db-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi