apiVersion: v1
kind: Secret
metadata:
  name: deploy-secret
  namespace: web
type: kubernetes.io/basic-auth 
stringData:                       # it can be data also but then you have to give the username and password in base 64 format
  username: admin                 # for base64 give command:  echo -n "admin" | base64
  password: admin123