apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: web
spec:
  type: LoadBalancer
  selector:
    app: webapp
  ports:
    - port: 5005
      targetPort: 5005
      nodePort: 30020